package my.mybatis.generator.auto.dao;

import java.util.List;
import my.mybatis.generator.auto.entity.ProcurementOrder;
import my.mybatis.generator.auto.entity.ProcurementOrderExample;
import org.apache.ibatis.annotations.Param;

public interface ProcurementOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    long countByExample(ProcurementOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int deleteByExample(ProcurementOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer subOrderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int insert(ProcurementOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int insertSelective(ProcurementOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    List<ProcurementOrder> selectByExample(ProcurementOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    ProcurementOrder selectByPrimaryKey(Integer subOrderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("row") ProcurementOrder row, @Param("example") ProcurementOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int updateByExample(@Param("row") ProcurementOrder row, @Param("example") ProcurementOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(ProcurementOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table procurement_order
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    int updateByPrimaryKey(ProcurementOrder row);
}