package my.mybatis.generator.auto.dao;

import java.util.List;
import my.mybatis.generator.auto.entity.StorageRecord;
import my.mybatis.generator.auto.entity.StorageRecordExample;
import org.apache.ibatis.annotations.Param;

public interface StorageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    long countByExample(StorageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int deleteByExample(StorageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer storageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int insert(StorageRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int insertSelective(StorageRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    List<StorageRecord> selectByExample(StorageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    StorageRecord selectByPrimaryKey(Integer storageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("row") StorageRecord row, @Param("example") StorageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int updateByExample(@Param("row") StorageRecord row, @Param("example") StorageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(StorageRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_record
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    int updateByPrimaryKey(StorageRecord row);
}