package my.mybatis.generator.auto.entity;

public class ProcurementOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.sub_orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer subOrderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.rfqID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer rfqid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.supplierID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer supplierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.UserID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.amount
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.materialID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Integer materialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column procurement_order.price
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.sub_orderID
     *
     * @return the value of procurement_order.sub_orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getSubOrderid() {
        return subOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.sub_orderID
     *
     * @param subOrderid the value for procurement_order.sub_orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setSubOrderid(Integer subOrderid) {
        this.subOrderid = subOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.orderID
     *
     * @return the value of procurement_order.orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.orderID
     *
     * @param orderid the value for procurement_order.orderID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.rfqID
     *
     * @return the value of procurement_order.rfqID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getRfqid() {
        return rfqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.rfqID
     *
     * @param rfqid the value for procurement_order.rfqID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setRfqid(Integer rfqid) {
        this.rfqid = rfqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.supplierID
     *
     * @return the value of procurement_order.supplierID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.supplierID
     *
     * @param supplierid the value for procurement_order.supplierID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.UserID
     *
     * @return the value of procurement_order.UserID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.UserID
     *
     * @param userid the value for procurement_order.UserID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.amount
     *
     * @return the value of procurement_order.amount
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.amount
     *
     * @param amount the value for procurement_order.amount
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.materialID
     *
     * @return the value of procurement_order.materialID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Integer getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.materialID
     *
     * @param materialid the value for procurement_order.materialID
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setMaterialid(Integer materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column procurement_order.price
     *
     * @return the value of procurement_order.price
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column procurement_order.price
     *
     * @param price the value for procurement_order.price
     *
     * @mbg.generated Mon Jul 25 12:40:41 GMT+08:00 2022
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}