package my.mybatis.generator.auto.entity;

public class ReceiveProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    private Integer receiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product.orderID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product. status
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product.receiveID
     *
     * @return the value of receive_product.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product.receiveID
     *
     * @param receiveid the value for receive_product.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product.orderID
     *
     * @return the value of receive_product.orderID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product.orderID
     *
     * @param orderid the value for receive_product.orderID
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product. status
     *
     * @return the value of receive_product. status
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product. status
     *
     * @param status the value for receive_product. status
     *
     * @mbg.generated Thu Jul 21 21:11:33 GMT+08:00 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}