package my.mybatis.generator.auto.entity;

import java.util.Date;

public class ReceiveProductDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer subReceiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer receiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.sub_orderID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer subOrderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.supplierID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer supplierid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.userID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.amount
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.materialID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Integer materialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.storage_location
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private String storageLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail.receive_date
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private Date receiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_product_detail. status
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.sub_receiveID
     *
     * @return the value of receive_product_detail.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getSubReceiveid() {
        return subReceiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.sub_receiveID
     *
     * @param subReceiveid the value for receive_product_detail.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setSubReceiveid(Integer subReceiveid) {
        this.subReceiveid = subReceiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.receiveID
     *
     * @return the value of receive_product_detail.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.receiveID
     *
     * @param receiveid the value for receive_product_detail.receiveID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.sub_orderID
     *
     * @return the value of receive_product_detail.sub_orderID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getSubOrderid() {
        return subOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.sub_orderID
     *
     * @param subOrderid the value for receive_product_detail.sub_orderID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setSubOrderid(Integer subOrderid) {
        this.subOrderid = subOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.supplierID
     *
     * @return the value of receive_product_detail.supplierID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.supplierID
     *
     * @param supplierid the value for receive_product_detail.supplierID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.userID
     *
     * @return the value of receive_product_detail.userID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.userID
     *
     * @param userid the value for receive_product_detail.userID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.amount
     *
     * @return the value of receive_product_detail.amount
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.amount
     *
     * @param amount the value for receive_product_detail.amount
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.materialID
     *
     * @return the value of receive_product_detail.materialID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Integer getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.materialID
     *
     * @param materialid the value for receive_product_detail.materialID
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setMaterialid(Integer materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.storage_location
     *
     * @return the value of receive_product_detail.storage_location
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public String getStorageLocation() {
        return storageLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.storage_location
     *
     * @param storageLocation the value for receive_product_detail.storage_location
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setStorageLocation(String storageLocation) {
        this.storageLocation = storageLocation == null ? null : storageLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail.receive_date
     *
     * @return the value of receive_product_detail.receive_date
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public Date getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail.receive_date
     *
     * @param receiveDate the value for receive_product_detail.receive_date
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setReceiveDate(Date receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_product_detail. status
     *
     * @return the value of receive_product_detail. status
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_product_detail. status
     *
     * @param status the value for receive_product_detail. status
     *
     * @mbg.generated Thu Jul 21 21:11:49 GMT+08:00 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }


}
