package my.mybatis.generator.auto.entity;

import java.util.Date;

public class StorageRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.storageID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private Integer storageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private Integer subReceiveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.material_name
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private String materialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.amount
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.storage_location
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private String storageLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.new_inventory
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private Integer newInventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_record.time
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.storageID
     *
     * @return the value of storage_record.storageID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public Integer getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.storageID
     *
     * @param storageid the value for storage_record.storageID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setStorageid(Integer storageid) {
        this.storageid = storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.sub_receiveID
     *
     * @return the value of storage_record.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public Integer getSubReceiveid() {
        return subReceiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.sub_receiveID
     *
     * @param subReceiveid the value for storage_record.sub_receiveID
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setSubReceiveid(Integer subReceiveid) {
        this.subReceiveid = subReceiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.material_name
     *
     * @return the value of storage_record.material_name
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.material_name
     *
     * @param materialName the value for storage_record.material_name
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.amount
     *
     * @return the value of storage_record.amount
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.amount
     *
     * @param amount the value for storage_record.amount
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.storage_location
     *
     * @return the value of storage_record.storage_location
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public String getStorageLocation() {
        return storageLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.storage_location
     *
     * @param storageLocation the value for storage_record.storage_location
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setStorageLocation(String storageLocation) {
        this.storageLocation = storageLocation == null ? null : storageLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.new_inventory
     *
     * @return the value of storage_record.new_inventory
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public Integer getNewInventory() {
        return newInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.new_inventory
     *
     * @param newInventory the value for storage_record.new_inventory
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setNewInventory(Integer newInventory) {
        this.newInventory = newInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_record.time
     *
     * @return the value of storage_record.time
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_record.time
     *
     * @param time the value for storage_record.time
     *
     * @mbg.generated Thu Jul 21 21:09:41 GMT+08:00 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }
}